-- =========================================================
-- STAFF & STORE PERFORMANCE ANALYSIS  (MySQL 8.0 syntax)
-- Covers: sales per staff, manager rollup, store comparison
-- =========================================================

-- ---------------------------------------------------------
-- SECTION A: SALES PER STAFF MEMBER
-- ---------------------------------------------------------

-- A1. Revenue, order count, and average order value per staff member
-- (only counts COMPLETED orders, since revenue on pending/rejected orders isn't realized yet)
SELECT
    s.staff_id,
    s.first_name,
    s.last_name,
    st.store_name,
    COUNT(DISTINCT o.order_id) AS num_orders,
    ROUND(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 2) AS total_revenue,
    ROUND(
        SUM(oi.quantity * oi.list_price * (1 - oi.discount)) / COUNT(DISTINCT o.order_id), 2
    ) AS avg_order_value
FROM staffs s
JOIN stores st ON st.store_id = s.store_id
LEFT JOIN orders o ON o.staff_id = s.staff_id AND o.order_status != 3
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY s.staff_id, s.first_name, s.last_name, st.store_name
ORDER BY total_revenue DESC;

-- A2. Staff hierarchy: who reports to whom
-- (manager_id references another staff_id; NULL manager_id = top of the org, e.g. a store manager)
SELECT
    s.staff_id,
    s.first_name,
    s.last_name,
    s.manager_id,
    m.first_name AS manager_first_name,
    m.last_name  AS manager_last_name
FROM staffs s
LEFT JOIN staffs m ON m.staff_id = s.manager_id
ORDER BY s.manager_id IS NULL DESC, s.manager_id, s.staff_id;

-- A3. Team-level rollup: total revenue generated by each manager's direct reports
WITH staff_revenue AS (
    SELECT
        s.staff_id,
        s.manager_id,
        COALESCE(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 0) AS revenue
    FROM staffs s
    LEFT JOIN orders o ON o.staff_id = s.staff_id AND o.order_status != 3
    LEFT JOIN order_items oi ON oi.order_id = o.order_id
    GROUP BY s.staff_id, s.manager_id
)
SELECT
    m.staff_id           AS manager_id,
    m.first_name         AS manager_first_name,
    m.last_name           AS manager_last_name,
    COUNT(sr.staff_id)    AS num_direct_reports,
    ROUND(SUM(sr.revenue), 2) AS team_total_revenue
FROM staff_revenue sr
JOIN staffs m ON m.staff_id = sr.manager_id
GROUP BY m.staff_id, m.first_name, m.last_name
ORDER BY team_total_revenue DESC;

-- A4. Ranking staff within their own store (who's the top performer at each location?)
SELECT
    st.store_name,
    s.staff_id,
    s.first_name,
    s.last_name,
    ROUND(COALESCE(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 0), 2) AS total_revenue,
    RANK() OVER (
        PARTITION BY st.store_id
        ORDER BY COALESCE(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 0) DESC
    ) AS rank_within_store
FROM staffs s
JOIN stores st ON st.store_id = s.store_id
LEFT JOIN orders o ON o.staff_id = s.staff_id AND o.order_status != 3
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY st.store_name, st.store_id, s.staff_id, s.first_name, s.last_name
ORDER BY st.store_name, rank_within_store;


-- ---------------------------------------------------------
-- SECTION B: STORE-LEVEL COMPARISON
-- ---------------------------------------------------------

-- B1. Store comparison: revenue, order count, average order size
SELECT
    st.store_id,
    st.store_name,
    st.city,
    st.state,
    COUNT(DISTINCT o.order_id) AS num_completed_orders,
    ROUND(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 2) AS total_revenue,
    ROUND(
        SUM(oi.quantity * oi.list_price * (1 - oi.discount)) / COUNT(DISTINCT o.order_id), 2
    ) AS avg_order_value,
    ROUND(SUM(oi.quantity) * 1.0 / COUNT(DISTINCT o.order_id), 2) AS avg_items_per_order
FROM stores st
LEFT JOIN orders o ON o.store_id = st.store_id AND o.order_status != 3
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY st.store_id, st.store_name, st.city, st.state
ORDER BY total_revenue DESC;

-- B2. Store comparison: fulfillment speed (ties back to operational efficiency, by store)
SELECT
    st.store_id,
    st.store_name,
    COUNT(*) AS num_completed_orders,
    ROUND(AVG(DATEDIFF(o.shipped_date, o.order_date)), 2) AS avg_days_to_ship,
    SUM(CASE WHEN o.shipped_date > o.required_date THEN 1 ELSE 0 END) AS num_late_orders,
    ROUND(SUM(CASE WHEN o.shipped_date > o.required_date THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS pct_late
FROM orders o
JOIN stores st ON st.store_id = o.store_id
WHERE o.order_status = 4 AND o.shipped_date IS NOT NULL
GROUP BY st.store_id, st.store_name
ORDER BY avg_days_to_ship;

-- B3. Combined store scorecard: revenue + fulfillment speed + staff count in one view
-- (revenue counts all non-rejected orders; avg_days_to_ship naturally ignores orders
--  that haven't shipped yet, since AVG() skips NULL shipped_date values)
SELECT
    st.store_id,
    st.store_name,
    (SELECT COUNT(*) FROM staffs sf WHERE sf.store_id = st.store_id AND sf.active = 1) AS active_staff_count,
    ROUND(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 2) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS num_orders,
    ROUND(AVG(DATEDIFF(o.shipped_date, o.order_date)), 2) AS avg_days_to_ship
FROM stores st
LEFT JOIN orders o ON o.store_id = st.store_id AND o.order_status != 3
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY st.store_id, st.store_name
ORDER BY total_revenue DESC;

-- B4. Revenue per active staff member, by store (a rough productivity/efficiency metric)
SELECT
    st.store_id,
    st.store_name,
    ROUND(SUM(oi.quantity * oi.list_price * (1 - oi.discount)), 2) AS total_revenue,
    (SELECT COUNT(*) FROM staffs sf WHERE sf.store_id = st.store_id AND sf.active = 1) AS active_staff_count,
    ROUND(
        SUM(oi.quantity * oi.list_price * (1 - oi.discount)) /
        NULLIF((SELECT COUNT(*) FROM staffs sf WHERE sf.store_id = st.store_id AND sf.active = 1), 0)
    , 2) AS revenue_per_active_staff
FROM stores st
LEFT JOIN orders o ON o.store_id = st.store_id AND o.order_status != 3
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY st.store_id, st.store_name
ORDER BY revenue_per_active_staff DESC;
